openapi: 3.0.0
info:
  title: Sample API
  description: Eli test of swagger
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: returns Eli's info.
      description: Eli's function.
      responses:
        '200':    # status code
          description: A json array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  description: test desciption
                  type: string
